# Generated by Django 4.2.28 on 2026-08-11 20:49

import classroom.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, default=classroom.models.generate_room_code, max_length=10, unique=True)),
                ('title', models.CharField(default='Huddle Live Session', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active_question', models.TextField(blank=True, null=True)),
                ('question_round', models.IntegerField(default=0)),
                ('correct_answer', models.CharField(blank=True, max_length=250, null=True)),
                ('is_revealed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='classroom.room')),
            ],
            options={
                'unique_together': {('room', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_round', models.IntegerField(default=0)),
                ('value', models.CharField(max_length=250)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='classroom.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='classroom.student')),
            ],
        ),
    ]
