# Generated by Django 4.2.30 on 2026-08-11 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='question_type',
            field=models.CharField(choices=[('SHORT_ANSWER', 'Short Answer'), ('MULTIPLE_CHOICE', 'Multiple Choice')], default='SHORT_ANSWER', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='quiz_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='student',
            name='is_whiteboard_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(default='Huddle Collaborative Session', max_length=200),
        ),
        migrations.CreateModel(
            name='WhiteboardStroke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stroke_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strokes', to='classroom.room')),
            ],
        ),
    ]
