# Generated by Django 4.2.30 on 2026-08-11 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_room_question_type_room_quiz_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_slide_index',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='slide_title',
            field=models.CharField(default='Lecture Presentation', max_length=200),
        ),
        migrations.AddField(
            model_name='room',
            name='total_slides',
            field=models.IntegerField(default=5),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('is_teacher', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='classroom.room')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
