# Generated by Django 4.2.30 on 2026-08-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_room_current_slide_index_room_slide_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slide_data_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
