# Generated by Django 4.2.30 on 2026-08-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_room_slide_data_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whiteboardstroke',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whiteboardstroke',
            name='student_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
