# Generated by Django 4.2.30 on 2026-08-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_chatmessage_is_private_chatmessage_recipient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_blank_whiteboard_mode',
            field=models.BooleanField(default=False),
        ),
    ]
