# Generated by Django 4.2.30 on 2026-08-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_room_is_blank_whiteboard_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_blank_whiteboard_mode',
        ),
        migrations.RemoveField(
            model_name='whiteboardstroke',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='whiteboardstroke',
            name='student_name',
        ),
        migrations.AddField(
            model_name='room',
            name='canvas_mode',
            field=models.CharField(default='pdf', max_length=20),
        ),
    ]
